# yaml-language-server: $schema=../Action.schema.json
apiVersion: make.new/v1alpha1
kind: Action
metadata:
  name: Call
spec:
  slug: call
  icon:
    type: FontAwesomeIcon
    name: phone
  services:
  - provider: Native
    name: Native Call
    icon:
      type: FontAwesomeIcon
      name: phone
    triggers:
      - type: LinkTrigger
        uri: tel://
