# yaml-language-server: $schema=../Action.schema.json
apiVersion: make.new/v1alpha1
kind: Action
metadata:
  name: Call
spec:
  slug: call
  icon:
    type: FontAwesomeIcon
    name: phone
  services:
  - provider: Native
    name: Native Call
    icon:
      type: FontAwesomeIcon
      name: phone
    triggers:
      - type: LinkTrigger
        uri: tel://
  - provider: FreeConferenceCall
    name: FreeConferenceCall
    icon:
      type: Image
      source: https://www.google.com/s2/favicons?domain=www.freeconferencecall.com&sz=32
    triggers:
      - type: LinkTrigger
        uri: https://www.freeconferencecall.com/profile
  - provider: PopTox
    name: PopTox
    icon:
      type: Image
      source: https://www.google.com/s2/favicons?domain=poptox.com&sz=32
    triggers:
      - type: LinkTrigger
        uri: https://www.poptox.com
