# yaml-language-server: $schema=../Action.schema.json
apiVersion: make.new/v1alpha1
kind: Action
metadata:
  name: Document
spec:
  slug: document
  icon:
    type: FontAwesomeIcon
    name: file
  services:
  - provider: Google
    name: Google Docs
    icon:
      type: Image
      source: https://www.google.com/s2/favicons?domain=docs.google.com&sz=32
    triggers:
      - type: LinkTrigger
        uri: https://docs.new
  - provider: Microsoft
    name: Microsoft Word
    icon:
      type: Image
      source: https://www.google.com/s2/favicons?domain=www.microsoft.com&sz=32
    triggers:
      - type: LinkTrigger
        uri: https://word.new
  - provider: Dropbox
    name: Dropbox Paper
    icon:
      type: Image
      source: https://www.google.com/s2/favicons?domain=www.dropbox.com&sz=32
    triggers:
      - type: LinkTrigger
        uri: https://paper.new
