apiVersion: make.new/v1alpha1
kind: Action
metadata:
  name: Document
spec:
  iconClass: fa-solid fa-file
  services:
  - provider: Google
    name: Google Docs
    url: https://docs.new
    icon: https://www.google.com/s2/favicons?domain=docs.google.com&sz=32
  - provider: Microsoft
    name: Microsoft Word
    url: https://word.new
    icon: https://www.google.com/s2/favicons?domain=www.microsoft.com&sz=32
  - provider: Dropbox
    name: Dropbox Paper
    url: https://paper.new
    icon: https://www.google.com/s2/favicons?domain=www.dropbox.com&sz=32
