# yaml-language-server: $schema=../schemas/action.json
apiVersion: make.new/v1alpha1
kind: Action
metadata:
  name: Document
spec:
  iconClass: fa-solid fa-file
  services:
  - provider: Google
    name: Google Docs
    icon: https://www.google.com/s2/favicons?domain=docs.google.com&sz=32
    trigger:
      - type: UriTrigger
        url: https://docs.new
  - provider: Microsoft
    name: Microsoft Word
    icon: https://www.google.com/s2/favicons?domain=www.microsoft.com&sz=32
    trigger:
      - type: UriTrigger
        url: https://word.new
  - provider: Dropbox
    name: Dropbox Paper
    icon: https://www.google.com/s2/favicons?domain=www.dropbox.com&sz=32
    trigger:
      - type: UriTrigger
        url: https://paper.new
