# yaml-language-server: $schema=../Action.schema.json
apiVersion: make.new/v1alpha1
kind: Action
metadata:
  name: Task
spec:
  slug: task
  icon:
    type: FontAwesomeIcon
    name: list-check
  services:
    - provider: Google
      name: Google Tasks
      icon:
        type: Image
        source: https://www.google.com/s2/favicons?domain=google.com&sz=32
      triggers:
        - type: LinkTrigger
          uri: https://tasks.google.com/embed/?origin=https://calendar.google.com&fullWidth=1
    - provider: Microsoft
      name: Microsoft To Do
      icon:
        type: Image
        source: https://www.google.com/s2/favicons?domain=microsoft.com&sz=32
      triggers:
        - type: LinkTrigger
          uri: https://to-do.office.com/tasks
