# yaml-language-server: $schema=../Action.schema.json
apiVersion: make.new/v1alpha1
kind: Action
metadata:
  name: Task
spec:
  slug: task
  icon:
    type: FontAwesomeIcon
    name: list-check
  services: []
